require 'rest-client'                                                                          # => true
require 'json'                                                                                 # => true
request = RestClient.get("https://morning-wildwood-77553.herokuapp.com/?address=11+Broadway")  # => <RestClient::Response 200 "{\"officials...">
body = request.body                                                                            # => "{\"officials\":{\"Vice-President of the United States\":[{\"urls\":[\"http://www.whitehouse.gov/\"],\"phones\":[\"(202) 456-1111\"],\"party\":\"Republican\",\"name\":\"Mike Pence\",\"channels\":[{\"type\":\"GooglePlus\",\"id\":\"+whitehouse\"},{\"type\":\"Facebook\",\"id\":\"whitehouse\"},{\"type\":\"Twitter\",\"id\":\"whitehouse\"}],\"address\":[{\"zip\":\"20500\",\"state\":\"DC\",\"line2\":\"1600 Pennsylvania Avenue NW\",\"line1\":\"The White House\",\"city\":\"Washington\"}]}],\"United States Senate\":[{\"urls\":[\"http://www.schumer.senate.gov/\"],\"photoUrl\":\"http://bioguide.congress.gov/bioguide/photo/S/S000148.jpg\",\"phones\":[\"(202) 224-6542\"],\"party\":\"Democratic\",\"name\":\"Charles E. Schumer\",\"channels\":[{\"type\":\"Facebook\",\"id\":\"chuckschumer\"},{\"type\":\"Twitter\",\"id\":\"SenSchumer\"},{\"type\":\"YouTube\",\"id\":\"SenatorSchumer\"}],\"address\":[{\"z...
parsed = JSON.parse(body)                                                                      # => {"officials"=>{"Vice-President of the United States"=>[{"urls"=>["http://www.whitehouse.gov/"], "phones"=>["(202) 456-1111"], "party"=>"Republican", "name"=>"Mike Pence", "channels"=>[{"type"=>"GooglePlus", "id"=>"+whitehouse"}, {"type"=>"Facebook", "id"=>"whitehouse"}, {"type"=>"Twitter", "id"=>"whitehouse"}], "address"=>[{"zip"=>"20500", "state"=>"DC", "line2"=>"1600 Pennsylvania Avenue NW", "line1"=>"The White House", "city"=>"Washington"}]}], "United States Senate"=>[{"urls"=>["http://www.schumer.senate.gov/"], "photoUrl"=>"http://bioguide.congress.gov/bioguide/photo/S/S000148.jpg", "phones"=>["(202) 224-6542"], "party"=>"Democratic", "name"=>"Charles E. Schumer", "channels"=>[{"type"=>"Facebook", "id"=>"chuckschumer"}, {"type"=>"Twitter", "id"=>"SenSchumer"}, {"type"=>"YouTube", "id"=>"SenatorSchumer"}], "address"=>[{"zip"=>"20510", "state"=>"DC", "line1"=>"322 Hart Senate Office...

puts parsed["officials"]["United States Senate"]  # => nil

# >> {"urls"=>["http://www.schumer.senate.gov/"], "photoUrl"=>"http://bioguide.congress.gov/bioguide/photo/S/S000148.jpg", "phones"=>["(202) 224-6542"], "party"=>"Democratic", "name"=>"Charles E. Schumer", "channels"=>[{"type"=>"Facebook", "id"=>"chuckschumer"}, {"type"=>"Twitter", "id"=>"SenSchumer"}, {"type"=>"YouTube", "id"=>"SenatorSchumer"}], "address"=>[{"zip"=>"20510", "state"=>"DC", "line1"=>"322 Hart Senate Office Building", "city"=>"Washington"}]}
# >> {"urls"=>["http://www.gillibrand.senate.gov/"], "photoUrl"=>"http://bioguide.congress.gov/bioguide/photo/G/G000555.jpg", "phones"=>["(202) 224-4451"], "party"=>"Democratic", "name"=>"Kirsten E. Gillibrand", "channels"=>[{"type"=>"Facebook", "id"=>"KirstenGillibrand"}, {"type"=>"Twitter", "id"=>"SenGillibrand"}, {"type"=>"YouTube", "id"=>"KirstenEGillibrand"}], "address"=>[{"zip"=>"20510", "state"=>"DC", "line1"=>"478 Russell Senate Office Building", "city"=>"Washington"}]}
